typography_spectrum: 0.4284014869481325
color:
  brandStrength: 0.14469005702994764
  lightness: 0.767458178801462
  saturation: 0.27246908633969724
  rhythmicContrast: 0.6818403697106987
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.9593135595787317
author:
  name: DareUC
  email: jmcusack@dareuc.com
name: jctest2
navigation:
  - name: Post 1
    id: 55f0990a-23ad-4fdb-a130-db34cbae8046
    type: content
  - name: bed time
    id: c2db939f-89ed-4d88-a7ed-ba3fc85b60df
    type: content
  - name: strange post
    id: 32741e90-4da2-40d0-98dd-68821c409f31
    type: content
  - name: Campaign
    id: 3c885e2d-d156-4522-ad1f-de18da9f06e2
    type: content
title: Energy and Telecomm Consulting
description: testing it now
